### PR TITLE
Fixed issue #3 Doesn't work properly on Ubuntu

### PR DESCRIPTION
**Pull request by snkasi**
Fix the bug
Modify content while print_multi_line() runs between "lines_of_content()" and "print(magic_char * (max(last_output_lines, lines)-1), end="")"

### CODE REVIEW

**Comment by Yinzo** [comment]
Sorry, can't get your point.
What is the purpose of making a deep copy of original content then assigning it back.

**Comment by snkasi** [comment]
When the value of  "content" changes between lines_of_content() (line.137)  and print_line() (line.150 or 154), the value of "lines" is unreliable, the number of rows to be going back may be inaccurate, using "copy" is a solution.

**Comment by Yinzo** [comment]
But all the assigning code within the [output lock](https://github.com/Yinzo/reprint/blob/master/reprint/reprint.py#L189), how is that `content` changeable ?

**Comment by snkasi** [comment]
However, it does not work for list.append()...

locker


['']
['', 'append']
locker_setitem
['change', 'appent']

**Comment by Yinzo** [comment]
You are right, `append` function for `list` is indeed missed, so I think I should add the `append` function into the lock area

**Comment by snkasi** [comment]
Don't froget extend(), pop(), remove() and insert().

**Comment by Yinzo** [comment]
so does `sort()`

**Comment by Yinzo** [comment]
Nice PR.But the commit history is a little messy, please make a new PR and use 'rebase' of git to get new commits from my original branch, and maybe drop the 'copy and reassign' part code.

please create a new PR and set the target to a new branch like `dev`, and I can also do some modify :-)

**Pull request closed without merging**
